# Generated by Django 5.0.2 on 2024-03-19 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_alter_team_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="small_img",
            new_name="img",
        ),
    ]
