import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SystemContextProvider } from '@context/useSystem.js';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SystemContextProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </SystemContextProvider>
  );
}
