version: "25.0.3"
services:
  app:
    build: .
    volumes: 
      - .:/django
    ports: 
      - 8000:8000
    image: teamlist:latest
    container_name: teamlist_container
    command: gunicorn setup.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env 