# Generated by Django 5.0.2 on 2024-04-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0003_alter_trophy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trophy',
            options={'ordering': ['name'], 'verbose_name': 'Troféu', 'verbose_name_plural': 'Troféus'},
        ),
    ]
