# Generated by Django 5.0.2 on 2024-02-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="eng_name",
            field=models.CharField(default=" ", max_length=255, verbose_name="Nome"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="country",
            name="iso_a3",
            field=models.CharField(
                default="Unknown", max_length=3, verbose_name="ISO A3"
            ),
            preserve_default=False,
        ),
    ]
