# Generated by Django 5.0.2 on 2024-03-02 01:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0002_country_eng_name_country_iso_a3"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"], "verbose_name_plural": "Countries"},
        ),
        migrations.RemoveField(
            model_name="country",
            name="eng_name",
        ),
        migrations.RemoveField(
            model_name="country",
            name="iso_a3",
        ),
    ]
