# Generated by Django 5.0.2 on 2024-03-08 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0002_team_id_country"),
        ("trophies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamTrophy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_trophy",
                        to="teams.team",
                    ),
                ),
                (
                    "id_trophy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_trophy",
                        to="trophies.trophy",
                    ),
                ),
            ],
            options={
                "db_table": "team_trophy",
            },
        ),
    ]
