# Generated by Django 5.0.2 on 2024-03-18 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0002_alter_country_options_country_background_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["name"],
                "verbose_name": "País",
                "verbose_name_plural": "Países",
            },
        ),
    ]
