# Generated by Django 5.0.2 on 2024-03-14 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trophies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trophy",
            options={"verbose_name_plural": "Trophies"},
        ),
    ]
