# Generated by Django 5.0.2 on 2024-03-18 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trophies", "0002_alter_trophy_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trophy",
            options={"verbose_name": "Troféu", "verbose_name_plural": "Troféus"},
        ),
    ]
