# Generated by Django 5.0.2 on 2024-03-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_trophy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamtrophy",
            options={
                "verbose_name": "Team Trophies",
                "verbose_name_plural": "Teams and Trophies",
            },
        ),
        migrations.AddField(
            model_name="teamtrophy",
            name="season",
            field=models.CharField(
                default="-", max_length=255, verbose_name="Temporada"
            ),
            preserve_default=False,
        ),
    ]
