# Generated by Django 5.0.2 on 2024-03-18 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team_trophy", "0002_alter_teamtrophy_options_teamtrophy_season"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamtrophy",
            options={
                "verbose_name": "Equipe e troféu",
                "verbose_name_plural": "Equipes e troféus",
            },
        ),
    ]
