# Generated by Django 5.0.2 on 2024-03-17 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stadiums", "__first__"),
        ("teams", "0002_team_id_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="country_img",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="team",
            name="id_stadium",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stadiums.stadium",
                verbose_name="Stadium",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="small_img",
            field=models.URLField(max_length=255),
        ),
    ]
