# Generated by Django 5.0.2 on 2024-03-18 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_alter_team_country_img_alter_team_id_stadium_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Equipe", "verbose_name_plural": "Equipes"},
        ),
    ]
