# Generated by Django 5.0.2 on 2024-04-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_rename_small_img_team_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
    ]
